# هوش‌یار — Backend (Phase-1 API implementation of the blueprint)
# Run:  uvicorn hooshyar_backend:app --port 8000   →  Docs: http://localhost:8000/docs
#
# STORAGE IS DECOUPLED FROM THIS SERVER (hooshyar_db.py): the app server is
# stateless/disposable — students, teachers, exams, attempts and mastery live
# in their OWN database, so a crashed server, a redeploy or a full host switch
# loses nothing:
#   • PostgreSQL (production):  HOOSHYAR_DSN=postgresql://user:pass@dbhost:5432/hooshyar
#   • SQLite (dev default):     HOOSHYAR_DB=/path/hooshyar.db  (file next to this script)
# Full-portability JSON backup/restore/migrate: tools/db_tool.py + GET /admin/backup.
#
# The "AI" lives behind the LLMAdapter interface (SimulatedLLM now, self-hosted
# vLLM in production — blueprint §4-B). Swapping is a config change, not a rewrite.
from __future__ import annotations
import json, math, random, re, time, base64, os
from typing import Optional
from fastapi import FastAPI, HTTPException, Depends, Header
from pydantic import BaseModel

import hooshyar_db    # pluggable storage core: SQLite ⇄ PostgreSQL, snapshots

KONKUR = lambda c, w, n: round((c * 3 - w) * 100 / (n * 3), 2) if n else 0.0

# ---------------------------------------------------------------- curriculum
# Single source of truth: hooshyar-prototype.html — hooshyar_questions.py is
# generated by `node tools/export_questions.js`; full ۶-year coverage (119 lessons, 15 subjects).
from hooshyar_questions import SUBJECTS, BANK, TASHRIHI

LESSON_SUBJECT = {l: sid for sid, sub in SUBJECTS.items() for l in sub["lessons"]}
LESSON_NAMES = {l: n for sub in SUBJECTS.values() for l, n in sub["lessons"].items()}
TEACHER_SUBJECTS = {   # subject scoping mirrors the prototype rules
    "t1": ["zist"], "t2": ["shimi"], "t3": ["fizik"], "t4": ["riazi"],
    "t5": ["adabyat"], "t6": ["arabi"], "t7": ["english"], "t8": ["zamin"], "t9": ["dini"],
    "t10": ["olum7", "olum8", "olum9"], "t11": ["riazi7", "riazi8", "riazi9"],
    "t12": ["mot7", "mot8", "mot9"],
}

# ---------------------------------------------------------------- AI adapter
def norm_fa(s: str) -> str:
    tr = str.maketrans("يإأةؤئك", "یااهویک")
    return re.sub(r"\s+", " ", (s or "").translate(tr)).strip()

class SimulatedLLM:
    """Phase-0 stand-in (templates). PRODUCTION (blueprint §4-B):
       class VLLMAdapter: POST to self-hosted vLLM /v1/chat/completions with
       textbook-RAG context; same method signatures, human approval stays on."""
    def generate_mcq(self, lesson: str, difficulty: int, rng: random.Random) -> dict:
        subject = next(s for s, v in SUBJECTS.items() if lesson in v["lessons"])
        if lesson == "ph":
            c = rng.choice([0.1, 0.05, 0.01, 0.005, 0.001]); acid = rng.choice(["HCl", "HNO3", "HBr"])
            pH_exact = -math.log10(c); pH = round(pH_exact) if pH_exact == int(pH_exact) else round(pH_exact, 1)
            opts = [pH, round(pH + 1, 1), max(1, round(pH - 1, 1)), round(14 - pH, 1)]
            return {"s": subject, "l": lesson, "d": 2, "src": "ai",
                    "q": f"غلظت اسید قوی {acid} برابر {c} مولار است. pH این محلول تقریباً کدام است؟",
                    "o": [str(x) for x in opts], "a": 0,
                    "exp": f"pH = −log({c}) ≈ {pH}"}
        v = rng.choice([8, 10, 12, 15, 18, 20, 25, 30]); t = rng.choice([3, 4, 5, 6, 8, 10]); x = v * t
        return {"s": subject, "l": lesson, "d": 1, "src": "ai",
                "q": f"متحرکی با تندی {v} m/s در {t} s چند متر جابه‌جا می‌شود؟",
                "o": [str(x), str(x + 20), str(max(10, x - 20)), str(v + t)], "a": 0,
                "exp": f"x = v×t = {x} m"}
    def grade_tashrihi(self, q: dict, text: str) -> dict:
        t = norm_fa(text); score = 0; hits = []
        for kw, w in q["kw"]:
            ok = norm_fa(kw) in t
            hits.append({"kw": kw, "w": w, "ok": ok})
            score += w if ok else 0
        return {"score": min(100, score), "hits": hits,
                "words": len(t.split()) if t else 0}
    def generate_tashrihi(self, lesson: str, difficulty: int, rng: random.Random) -> dict:
        """آزمون کاملاً تشریحی: process-focused stems (توضیح/مثال/مراحل) with NO
        invented facts — facts live in the teacher-approved model answer (Gate-A).
        Mirrors TASH_STEMS in the prototype."""
        name = LESSON_NAMES.get(lesson, lesson)
        subject = LESSON_SUBJECT.get(lesson, "")
        stems = [
            f"مفهوم «{name}» را با زبان خودتان توضیح دهید و یک مثال از کتاب درسی برای آن بیاورید.",
            f"دو نکتهٔ کلیدی مبحث «{name}» را بنویسید و برای هرکدام یک مثال بزنید.",
            f"مراحل حل یک مسئله از «{name}» را به‌ترتیب بنویسید و دلیل هر مرحله را ذکر کنید.",
            f"یک سؤال امتحانی از مبحث «{name}» طراحی کنید و سپس پاسخ تشریحی کامل آن را بنویسید.",
            f"یک اشتباه رایج دانش‌آموزان در «{name}» را با یک مثال توضیح دهید و روش درست را بنویسید.",
            f"«{name}» را آن‌قدر شفاف توضیح دهید که یک هم‌کلاسی شما یاد بگیرد؛ توضیح را با یک مثال همراه کنید.",
        ]
        return {"s": subject, "l": lesson, "d": max(1, min(5, difficulty or 3)),
                "type": "tashrihi", "src": "ai", "q": rng.choice(stems),
                "model": f"پاسخ کامل باید تعریف/قاعدهٔ «{name}» + یک مثال درست از کتاب درسی + توضیح مراحل را پوشش دهد. (روبریک پیشنهادی 🤖 — معلم بازبینی می‌کند)",
                "kw": [[name, 50], ["مثال", 25], ["توضیح", 25]]}

LLM = SimulatedLLM()  # ← production: VLLMAdapter(endpoint=..., model=...)

# ---------------------------------------------------------------- database
# Thin aliases so callers/tests keep `with hb.db() as con:` + `hb.init_db(con)`.
# Engine selection, `?`-placeholder translation and the context-manager
# contract all live in hooshyar_db.Conn — SQL here never changes per engine.
def db() -> hooshyar_db.Conn:
    return hooshyar_db.connect()

def init_db(con: hooshyar_db.Conn):
    hooshyar_db.create_schema(con)
    if not con.execute("SELECT 1 FROM users LIMIT 1").fetchone():
        con.execute("INSERT INTO users VALUES(?,?,?,?)", ("b1", "admin", "مدیر مدرسه", None))
        tnames = {"t1": "معلم زیست‌شناسی", "t2": "معلم شیمی", "t3": "معلم فیزیک", "t4": "معلم ریاضی",
                  "t5": "معلم ادبیات فارسی", "t6": "معلم عربی", "t7": "معلم زبان انگلیسی",
                  "t8": "معلم زمین‌شناسی", "t9": "معلم دین و زندگی",
                  "t10": "معلم علوم — دورهٔ اول", "t11": "معلم ریاضی — دورهٔ اول",
                  "t12": "معلم مطالعات اجتماعی — دورهٔ اول"}
        for tid, tname in tnames.items():
            con.execute("INSERT INTO users VALUES(?,?,?,?)", (tid, "teacher", tname,
                        json.dumps({"subjects": TEACHER_SUBJECTS[tid]}, ensure_ascii=False)))
        # real school classes: هفتم/هشتم/نهم (دورهٔ اول متوسطه) + grade×major (دورهٔ دوم)
        # demo roster: 2 students per class — s0,s1→هفتم … s16,s17→دوازدهم ریاضی
        class_list = ["هفتم", "هشتم", "نهم", "دهم تجربی", "یازدهم تجربی", "دوازدهم تجربی",
                      "دهم ریاضی", "یازدهم ریاضی", "دوازدهم ریاضی"]
        for i, n in enumerate(["علی", "سارا", "محمد", "نگار", "پارسا", "یاسمین", "آرش", "مریم",
                               "دانیال", "ترانه", "کیان", "روژینا", "فرهاد", "سوگند", "امیرحسین",
                               "رها", "آرمان", "سارینا"]):
            con.execute("INSERT INTO users VALUES(?,?,?,?)", (f"s{i}", "student", n, json.dumps({"class": class_list[i // 2]}, ensure_ascii=False)))
    con.commit()

# ---------------------------------------------------------------- auth
def token(uid: str, role: str) -> str:
    return base64.urlsafe_b64encode(f"{role}:{uid}".encode()).decode()

def auth(authorization: Optional[str] = Header(None)):
    if not authorization: raise HTTPException(401, "token missing")
    try:
        role, uid = base64.urlsafe_b64decode(authorization.replace("Bearer ", "")).decode().split(":")
    except Exception: raise HTTPException(401, "bad token")
    with db() as con:
        u = con.execute("SELECT * FROM users WHERE id=?", (uid,)).fetchone()
    if not u or u["role"] != role: raise HTTPException(403, "unknown user")
    return {"id": uid, "role": role, "name": u["name"]}

def teacher(user=Depends(auth)):
    if user["role"] != "teacher": raise HTTPException(403, "teachers only")
    return user

def admin(user=Depends(auth)):
    if user["role"] != "admin": raise HTTPException(403, "admins only")
    return user

def staff(user=Depends(auth)):
    if user["role"] not in ("teacher", "admin"): raise HTTPException(403, "staff only")
    return user

# ---------------------------------------------------------------- core logic
def grade_mcq(qs: list, ans: list) -> dict:
    c = w = b = 0; per_l: dict = {}; tash = []
    for i, q in enumerate(qs):
        if q.get("type") == "tashrihi":
            tash.append({"i": i, "q": q, "grade": LLM.grade_tashrihi(q, ans[i] or "")}); continue
        x = per_l.setdefault(q["l"], {"c": 0, "w": 0, "b": 0, "t": 0}); x["t"] += 1
        r = ans[i]
        if r is None: b += 1; x["b"] += 1
        elif r == q["a"]: c += 1; x["c"] += 1
        else: w += 1; x["w"] += 1
    n = len(qs) - len(tash)
    if n:
        pct = KONKUR(c, w, n)
    elif tash:   # آزمون کاملاً تشریحی: headline grade = mean of rubric scores
        pct = round(sum((x["grade"].get("final") if x["grade"].get("final") is not None else x["grade"]["score"]) for x in tash) / len(tash), 1)
    else:
        pct = 0.0
    return {"c": c, "w": w, "b": b, "pct": pct, "perL": per_l, "tashrihi": tash, "n": n}

def lesson_pct(x: dict) -> float: return KONKUR(x["c"], x["w"], x["t"])

def mastery(con, uid: str) -> dict:
    out = {}
    for row in con.execute("SELECT lesson,p,t FROM stats WHERE user_id=? ORDER BY t", (uid,)):
        out.setdefault(row["lesson"], []).append({"p": row["p"], "t": row["t"]})
    res = {}
    for lid, tries in out.items():
        last, avg = tries[-1]["p"], sum(x["p"] for x in tries) / len(tries)
        age = (time.time() - tries[-1]["t"]) / 86400
        m = max(0, min(100, round(0.55 * last + 0.45 * avg)))
        res[lid] = {"m": m, "n": len(tries), "age_days": round(age)}
    return res

def build_plan(con, uid: str, rng: random.Random) -> dict:
    ms = mastery(con, uid)
    rows = []
    for sid, sub in SUBJECTS.items():
        for lid, lname in sub["lessons"].items():
            m = ms.get(lid, {}).get("m", 30); age = ms.get(lid, {}).get("age_days", 21)
            rows.append({"lid": lid, "name": lname, "coef": sub["coef"], "m": m,
                         "pr": (100 - m) * sub["coef"] * (1 + 0.5 * min(age, 21) / 21)})
    rows.sort(key=lambda r: -r["pr"])
    days = ["شنبه", "یکشنبه", "دوشنبه", "سه‌شنبه", "چهارشنبه", "پنجشنبه", "جمعه"]
    plan = {d: [] for d in days}
    for i, r in enumerate(rows[:9]):
        plan[days[i % 6]].append({"topic": r["name"], "mins": 35 + (i % 3) * 10,
                                  "stars": 3 if r["pr"] > 140 else 2 if r["pr"] > 80 else 1})
    weak = [r["name"] for r in rows if r["m"] < 50][:3]
    plan["پنجشنبه"].append({"topic": "آزمون کوتاه ۱۵ تایی از مباحث ضعیف: " + ("، ".join(weak) or "مباحث اخیر"), "mins": 40, "stars": 3})
    plan["جمعه"].append({"topic": "استراحت + مرور اشتباهات", "mins": 20, "stars": 1})
    return plan

# ---------------------------------------------------------------- schemas
class LoginIn(BaseModel): uid: str
class GenIn(BaseModel):
    lessons: list[str]; count: int = 10; level: str = "mix"; title: Optional[str] = None
    kind: str = "mix"   # mix = تستی+تشریحی · mcq = فقط تستی · tashrihi = کاملاً تشریحی (سبک نهایی)
class AttemptIn(BaseModel): exam_id: str; answers: list
class TashrihiAdj(BaseModel): grade_idx: int; final: int

# ---------------------------------------------------------------- app
app = FastAPI(title="Hooshyar API", version="0.1.0")

# The HTML prototype runs from file:// or another origin — allow cross-origin
# calls from anywhere (prototype/demo only; restrict to school domains in prod).
from fastapi.middleware.cors import CORSMiddleware
app.add_middleware(
    CORSMiddleware, allow_origins=["*"], allow_credentials=False,
    allow_methods=["*"], allow_headers=["*"],
)

@app.on_event("startup")
def _start():
    with db() as con: init_db(con)

@app.get("/health")
def health():
    # db:engine/target report which datastore this instance is attached to
    return {"ok": True, "llm": type(LLM).__name__, **hooshyar_db.describe()}

@app.get("/admin/backup")
def admin_backup(user=Depends(admin)):
    """Full portable JSON snapshot of EVERYTHING (students, teachers, exams,
    attempts, mastery). Download it from any live instance and restore offline
    onto any server/engine:  python tools/db_tool.py restore backup.json
    The browser-app equivalent (demo data) is the app's own پشتیبان button."""
    with db() as con:
        return hooshyar_db.snapshot(con)

@app.post("/auth/login")
def login(body: LoginIn):
    with db() as con:
        u = con.execute("SELECT * FROM users WHERE id=?", (body.uid,)).fetchone()
    if not u: raise HTTPException(404, "user not found")
    return {"token": token(u["id"], u["role"]), "role": u["role"], "name": u["name"]}

@app.get("/taxonomy")
def taxonomy(user=Depends(auth)):
    return SUBJECTS

@app.get("/users/students")
def students(user=Depends(staff)):
    with db() as con:
        return [dict(r) for r in con.execute("SELECT id,role,name,profile FROM users WHERE role='student'")]

@app.post("/exams/generate")
def generate(body: GenIn, user=Depends(teacher)):
    rng = random.Random()
    known = [l for s in SUBJECTS.values() for l in s["lessons"]]
    # subject scoping (سروری): a teacher can only generate from their own subject(s)
    subs = TEACHER_SUBJECTS.get(user["id"])
    own = [l for l in known if not subs or LESSON_SUBJECT[l] in subs]
    wanted = [l for l in body.lessons if l in own]
    if body.lessons and not wanted:   # asked ONLY out-of-scope lessons -> fall back to own subject
        wanted = own
    t_pool = [dict(t, src="bank", approved=True, type="tashrihi") for t in TASHRIHI if not wanted or t["l"] in wanted]
    if body.kind == "tashrihi":
        # آزمون کاملاً تشریحی (بدون هیچ سؤال تستی، سبک امتحان نهایی): verified bank
        # tashrihi first; SimulatedLLM drafts top it up and WAIT for approval (Gate-A)
        rng.shuffle(t_pool)
        qs = t_pool[:body.count]
        les = wanted or own or known; i = 0
        while len(qs) < body.count and les:
            g = LLM.generate_tashrihi(les[i % len(les)], 3, rng)
            g.update(id=f"ait{i}", approved=False); qs.append(g); i += 1
        qs = qs[:body.count]
    else:
        pool = [dict(q, src="bank", approved=True) for q in BANK if not wanted or q["l"] in wanted]
        if body.level == "easy": pool = [q for q in pool if q["d"] <= 2]
        elif body.level == "mid": pool = [q for q in pool if q["d"] == 3]
        elif body.level == "hard": pool = [q for q in pool if q["d"] >= 4]
        rng.shuffle(pool)
        want_ai = max(1, round(body.count * 0.4))
        qs = pool[:max(0, body.count - want_ai)]
        les = wanted or own or known
        seen_q = {q["q"] for q in qs}
        while len(qs) < body.count:
            for _try in range(6):                       # avoid near-duplicate AI drafts
                g = LLM.generate_mcq(rng.choice(les), 2, rng)
                perm = list(range(4)); rng.shuffle(perm)
                g["o"] = [g["o"][p] for p in perm]; g["a"] = perm.index(g["a"])
                if g["q"] not in seen_q: break
            seen_q.add(g["q"])
            g.update(id=f"ai{len(qs)}", approved=False); qs.append(g)
        if len(qs) > body.count: qs = qs[:body.count]
        if body.kind != "mcq":   # «فقط تستی» skips the نهایی-style riders
            qs += t_pool[: 2 if body.count >= 15 else 1 if body.count >= 5 else 0]
    eid = f"e{int(time.time()*1000)}"
    title = body.title or (f"آزمون تشریحی {len(qs)} سؤالی" if body.kind == "tashrihi" else f"آزمون {len(qs)} سؤالی")
    with db() as con:
        con.execute("INSERT INTO exams VALUES(?,?,?,?,0,?)", (eid, user["id"], title, json.dumps(qs, ensure_ascii=False), time.time()))
    return {"exam_id": eid, "title": title, "qs": qs}

@app.post("/exams/{eid}/approve")
def approve(eid: str, user=Depends(teacher)):
    with db() as con:
        r = con.execute("SELECT qs FROM exams WHERE id=?", (eid,)).fetchone()
        if not r: raise HTTPException(404, "not found")
        qs = json.loads(r["qs"])
        for q in qs: q["approved"] = True
        con.execute("UPDATE exams SET qs=? WHERE id=?", (json.dumps(qs, ensure_ascii=False), eid))
    return {"approved": len(qs)}

@app.post("/exams/{eid}/publish")
def publish(eid: str, user=Depends(teacher)):
    with db() as con:
        qs = json.loads(con.execute("SELECT qs FROM exams WHERE id=?", (eid,)).fetchone()["qs"])
        if any(not q.get("approved") for q in qs):
            raise HTTPException(400, "unapproved AI questions — approve first (Gate-A rule)")
        con.execute("UPDATE exams SET published=1 WHERE id=?", (eid,))
    return {"published": eid}

@app.get("/exams/published")
def published(user=Depends(auth)):
    with db() as con:
        rows = con.execute("SELECT id,title FROM exams WHERE published=1 ORDER BY at DESC").fetchall()
        mine = {r["exam_id"]: r["res"] for r in con.execute("SELECT exam_id,res FROM attempts WHERE user_id=?", (user["id"],))}
    return [{"exam_id": r["id"], "title": r["title"],
             "my_pct": json.loads(mine[r["id"]])["pct"] if r["id"] in mine else None} for r in rows]

@app.get("/exams/{eid}")
def get_exam(eid: str, user=Depends(auth)):
    with db() as con:
        r = con.execute("SELECT * FROM exams WHERE id=?", (eid,)).fetchone()
    if not r: raise HTTPException(404, "not found")
    qs = json.loads(r["qs"])
    safe = [{k: v for k, v in q.items() if k not in ("a", "exp", "model", "kw")} for q in qs]
    return {"exam_id": eid, "title": r["title"], "qs": safe, "duration_min": len(qs)}

@app.post("/attempts")
def attempt(body: AttemptIn, user=Depends(auth)):
    with db() as con:
        r = con.execute("SELECT qs FROM exams WHERE id=?", (body.exam_id,)).fetchone()
        if not r: raise HTTPException(404, "not found")
        qs = json.loads(r["qs"])
        if len(body.answers) != len(qs): raise HTTPException(400, "answers length mismatch")
        res = grade_mcq(qs, body.answers)
        aid = f"a{int(time.time()*1000)}{user['id']}"
        con.execute("INSERT INTO attempts VALUES(?,?,?,?,?,?)",
                    (aid, body.exam_id, user["id"], json.dumps(body.answers, ensure_ascii=False), json.dumps(res, ensure_ascii=False), time.time()))
        for lid, x in res["perL"].items():
            con.execute("INSERT INTO stats VALUES(?,?,?,?)", (user["id"], lid, lesson_pct(x), time.time()))
        for x in res["tashrihi"]:
            con.execute("INSERT INTO stats VALUES(?,?,?,?)", (user["id"], x["q"]["l"], x["grade"]["score"], time.time()))
        con.commit()
    return res | {"attempt_id": aid}

@app.get("/students/{uid}/mastery")
def get_mastery(uid: str, user=Depends(auth)):
    if user["role"] != "teacher" and user["id"] != uid: raise HTTPException(403, "forbidden")
    with db() as con: return mastery(con, uid)

@app.get("/students/{uid}/plan")
def get_plan(uid: str, user=Depends(auth)):
    if user["role"] != "teacher" and user["id"] != uid: raise HTTPException(403, "forbidden")
    with db() as con: return build_plan(con, uid, random.Random())

@app.get("/class/heatmap")
def heatmap(user=Depends(staff)):
    with db() as con:
        studs = con.execute("SELECT id,name,profile FROM users WHERE role='student'").fetchall()
        matrix = []
        for s in studs:
            ms = mastery(con, s["id"])
            klass = None
            try: klass = json.loads(s["profile"] or "{}").get("class")
            except Exception: pass
            matrix.append({"student": s["name"], "id": s["id"], "class": klass, "per_lesson": ms,
                           "avg": round(sum(v["m"] for v in ms.values()) / len(ms), 1) if ms else None})
    return matrix

@app.get("/class/results")
def class_results(user=Depends(staff)):
    with db() as con:
        rows = con.execute("""
          SELECT e.title AS et, u.name AS un, a.res AS ar
          FROM attempts a JOIN exams e ON e.id=a.exam_id JOIN users u ON u.id=a.user_id
          WHERE e.published=1 ORDER BY a.at DESC""").fetchall()
    # pct extracted in Python — keeps the query identical on SQLite & PostgreSQL
    return [{"title": r["et"], "name": r["un"], "pct": json.loads(r["ar"])["pct"]} for r in rows]

# ---------------------------------------------------------------- admin panel
@app.get("/admin/overview")
def admin_overview(user=Depends(admin)):
    """Boss dashboard: school-wide KPIs at a glance."""
    with db() as con:
        studs = con.execute("SELECT id,profile FROM users WHERE role='student'").fetchall()
        teachers = con.execute("SELECT id,name FROM users WHERE role='teacher'").fetchall()
        exams = con.execute("SELECT id,published,at FROM exams").fetchall()
        attempts = con.execute("SELECT user_id,res FROM attempts").fetchall()
        per_student: dict = {}
        for a in attempts: per_student.setdefault(a["user_id"], []).append(json.loads(a["res"])["pct"])
        active = len(per_student)
        avg_pct = round(sum(p for v in per_student.values() for p in v) / max(1, sum(len(v) for v in per_student.values())), 1) if attempts else None
        lessons_seen = con.execute("SELECT COUNT(DISTINCT lesson) n FROM stats").fetchone()["n"]
        staff_exams = {t["name"]: con.execute("SELECT COUNT(*) n FROM exams WHERE creator=?", (t["id"],)).fetchone()["n"] for t in teachers}
        klass_counts = {}
        for s in studs:
            try: k = json.loads(s["profile"] or "{}").get("class", "—")
            except Exception: k = "—"
            klass_counts[k] = klass_counts.get(k, 0) + 1
    return {
        "students": len(studs), "teachers": len(teachers), "classes": klass_counts,
        "exams_total": len(exams), "exams_published": sum(1 for e in exams if e["published"]),
        "attempts": len(attempts), "active_students": active,
        "participation_pct": round(active / max(1, len(studs)) * 100),
        "school_avg_pct": avg_pct, "lessons_assessed": lessons_seen,
        "exams_by_teacher": staff_exams,
    }

@app.get("/admin/classes")
def admin_classes(user=Depends(admin)):
    """Boss dashboard: per-class mastery comparison (six classes: grade × major)."""
    with db() as con:
        studs = con.execute("SELECT id,name,profile FROM users WHERE role='student'").fetchall()
        out = {}
        for s in studs:
            try: k = json.loads(s["profile"] or "{}").get("class", "—")
            except Exception: k = "—"
            ms = mastery(con, s["id"])
            avg = round(sum(v["m"] for v in ms.values()) / len(ms), 1) if ms else None
            c = out.setdefault(k, {"class": k, "students": [], "avg": None, "per_lesson": {}})
            c["students"].append({"id": s["id"], "name": s["name"], "avg": avg})
            for lid, v in ms.items():
                c["per_lesson"].setdefault(lid, []).append(v["m"])
        for c in out.values():
            vals = [s["avg"] for s in c["students"] if s["avg"] is not None]
            c["avg"] = round(sum(vals) / len(vals), 1) if vals else None
            c["per_lesson"] = {lid: round(sum(v) / len(v)) for lid, v in c["per_lesson"].items()}
    return list(out.values())

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
