// Single-source truth: hooshyar-prototype.html → hooshyar_questions.py
// run: node tools/export_questions.js
const fs = require('fs');
const path = require('path');
const html = fs.readFileSync(path.join(__dirname, '..', 'hooshyar-prototype.html'), 'utf8');
const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m => m[1]);
eval(scripts.join('\n;\n'));
const H = module.exports;
const out = { SUBJECTS: {}, BANK: [], TASHRIHI: [] };
for (const s of H.SUBJECTS) {
  out.SUBJECTS[s.id] = { name: s.name, coef: s.coef, lessons: {} };
  for (const l of s.lessons) out.SUBJECTS[s.id].lessons[l.id] = l.name;
}
for (const q of H.BANK) {
  if (q.type === 'tashrihi') out.TASHRIHI.push({ id: q.id, s: q.s, l: q.l, d: q.d, q: q.q, model: q.model, kw: q.kw, ...(q.n ? { n: q.n } : {}), ...(q.y ? { y: q.y } : {}), ...(q.exp ? { exp: q.exp } : {}) });
  else out.BANK.push({ id: q.id, s: q.s, l: q.l, d: q.d, q: q.q, o: q.o.map(String), a: q.a, ...(q.exp ? { exp: q.exp } : {}), ...(q.k ? { k: q.k } : {}), ...(q.y ? { y: q.y } : {}) });
}
const py = `# AUTO-GENERATED by tools/export_questions.js — DO NOT EDIT BY HAND.
# Source of truth: hooshyar-prototype.html (SUBJECTS + BANK blocks).
# Re-run:  node tools/export_questions.js
SUBJECTS = ${JSON.stringify(out.SUBJECTS, null, 1)}
BANK = ${JSON.stringify(out.BANK, null, 1)}
TASHRIHI = ${JSON.stringify(out.TASHRIHI, null, 1)}
`;
fs.writeFileSync(path.join(__dirname, '..', 'hooshyar_questions.py'), py);
console.log(`exported: ${Object.keys(out.SUBJECTS).length} subjects, ${out.BANK.length} MCQ, ${out.TASHRIHI.length} tashrihi`);
